{% set python_min = "3.10" %}
{% set name = "pymatviz" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: a527ece0e361fc160fa27999e0600e46cc6747c60a6bb11bef64f913255e34c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=71
    - pip
  run:
    - python >={{ python_min }}
    - monty >=2024.10.21
    - matplotlib-base >=3.9
    - numpy >=1.26
    - pandas >=2.2
    - plotly >=5.23
    - pymatgen >=2024.11.13
    - scikit-learn >=1.5
    - scipy >=1.14

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
