{% set python_min = "3.10" %}
{% set name = "pymatviz" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: 911da6ee4a6741454e8ef344957f3736cb5a203acb245335da75218c3954a7c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=71
    - pip
  run:
    - moyopy >=0.4.1
    - python-kaleido ==0.2.1
    - pyyaml >=6
    - python >={{ python_min }}
    - monty >=2024.10.21
    - matplotlib-base >=3.9
    - numpy >=1.26
    - pandas >=2.2
    - plotly >=5.23
    - pymatgen >=2025.2.18
    - scikit-learn >=1.5
    - scipy >=1.14

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
