{% set name = "pymatviz" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: 3be8722a4bbfcbdb9505f52eb621959ac728d1818d4b1bd1e28548cff44979e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.6.2
    - numpy >=1.21.0
    - pandas
    - plotly
    - pymatgen
    - scikit-learn
    - scipy

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
