{% set name = "pymatviz" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: b3a5b77b2a256e148fc5c81cf5a5ba8807713e34cf1572f0bf20efc7254e38e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - monty >=2024.10.21
    - python >=3.10
    - matplotlib-base >=3.9
    - numpy >=1.26
    - pandas >=2.2
    - plotly >=5.23
    - pymatgen >=2024.11.13
    - scikit-learn >=1.5
    - scipy >=1.14

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
