{% set name = "pymatviz" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: 631d42bfe6b5c60753af6de28b3b65be6751dc89547879b43b4f7705d1234f43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.9
    - numpy >=1.26
    - pandas >=2.2
    - plotly >=5.23
    - pymatgen >=2024.7.18
    - scikit-learn >=1.5
    - scipy >=1.14

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
