{% set name = "pymatviz" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymatviz-{{ version }}.tar.gz
  sha256: 78ddda3d55104a536e0fab303fc01ce9ddea9f7ea535bbbdd34ef56aaa500d1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.6.2
    - numpy >=1.21.0,<2
    - pandas >=2.0.0
    - plotly
    - pymatgen
    - scikit-learn
    - scipy

test:
  imports:
    - pymatviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janosh/pymatviz
  summary: A toolkit for visualizations in materials informatics
  license: MIT
  license_file: license

extra:
  recipe-maintainers:
    - ocefpaf
